travis:
  secure:
    BINSTAR_TOKEN: 0SzF3AkhSULbBhDlo62uJQzGy1bqVTkrfZr0Ad4VjcrOlGsIBPGLvS52qnH3/58E96u/KS3930PoEvvK2nP7ICfK74q7xZcLRpVAwwdTHDxgRGRvZWprlVD2fH9JQB5kleEobU5B2eYucvU4lNxkRafno4oZUHDzipsOV9vYJEMhXGg0cycVWePNSl90Kcsegh5VBuRhnLwRgpdaVHuqTWBLkQUn8wSOjaAyWZ8jGIiJ613Z6vgncYJpypjOoXf3dDRyZtcMkY9fKzXO12Ip8SDpc2O9lHG1YAyq/ZKx+LEeE2N7DDNqPegpbaa9sktkSwg/FHaDUrDu14wQbBKpScw+G1Bw7zzcZN7wNXj4jKqt8c11fCXLFR9SN8AhnqAHUCQokVuKeEqPewtCPxK8CuHJ8k55cEM1Y8SRk1K/sUZ/kCNg5FRj4lo5ysOpocJH3ZGwumuNT9pjIiVWjTB5KehdQQ7Mn/7JNxRQU+Z+WejOMIr5Abl6+eeDtX03kKGh+tBk1FPAA2vkQhIhNTobJ0M8ofKtmuJhhD/bQRNfRkUCYWztW94nvBtqiIuJmomIbXvGEuImcZoE4qUsX9RdnfH8nYjgz8EydR0PFUQNFKIwLgGd3cR7QlxYDALtoiMMT6ZjbMhmfV95WBZ0f8VsU3QYO+KqZxNeSu/rnXJe1GU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
