travis:
  secure:
    BINSTAR_TOKEN: K7B6TyTBgaD1+bEb/UbvH7lHFXqQasuk7w+vTZDtFA7d95bWzx7J4hZ96p+JpDszHeK+B3dO/qgbvSbzbbdUwGFNWcN1DMNmIdnterllDpfZnUcnTUicyNMLkwmuAx3yM2wg8NqidTErErIywvEYsNPNC7VvnHWdWV4ZZ4qaUbNUqSjfdnsF1bsPaBlLjmD3FyK+4IjeMN+ri48qme34dtHpBzka6L8c7StgDDAfAEBeH6qdb6ho6xSWJNgQLeOphgldUd8ef3pv0AfaEfjHDjxdijeaTm/hznmDfpp3q7FrUj/FpEp3iVJDcjAHX7QAwQAaOeXhFRVWW8HUv0t+Ff54AjppAN7MYpdy2ykh/E46FuSYynnN/lWoXI370KOSSlBG1+gCsyG5clZWT5B1oadXf/TL3KKKskLBfkFYXBP34OcHfrNMoJ3H78Ow04ac2Au74GTFlzExBekPyuqLpKftW3N0HHkJR+nypNWRPkX95LzcKNuHK8K0DGrPVP7W3krWfsaI81wC+gclcbmg1AtvbeV9mu/ooNjIqjW0kHuYvw+HWqCRn5Wo50SDGx3t/ZA6PC53qUdWcYrn28pTqpP7ozBWRsEJ7AFZ5KdfM88eQBXhlnhbYDQCMtC/ebKACngHuWTSkPkyUcaCPOzfwkrWZ6jkp0c5p9/jgOhf8oA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
